---
# tasks file for api

- name: "Configure Flask API server"
  template:
        src: "mysql.env.j2"
        dest: "/home/ubuntu/api_server/mysql.env"
        owner: "ubuntu"
        group: "ubuntu"
        mode: 0644

- name: Get fitcycle PID
  shell: "ps -ef | grep -v grep | grep -w api_server.py | awk '{print $2}'"
  register: api_py_process

- name: Stop API server
  shell: "kill -9 {{ item }}"
  with_items: "{{ api_py_process.stdout_lines }}"
  ignore_errors: yes 

- name: Start API server
  shell: ./startapi.sh & chdir=/home/ubuntu/api_server

- name: App is deployed and ready
  debug:
    msg: "App load balanced at following IPs: {{ groups['tag_Tier_WEB'] }}"
