- name: "Copy Django settings file"
  template:
        src: "settings.py.j2"
        dest: "/home/ubuntu/fitcycle/fitcycle/settings.py"
        owner: "ubuntu"
        group: "ubuntu"
        mode: 0644

- name: Get Fitcycle pid
  shell: "ps -ef | grep -v grep | grep -w manage.py | awk '{print $2}'"
  register: manage_py_process

- name: Stop fitcycle app
  shell: "kill -9 {{ item }}"
  with_items: "{{ manage_py_process.stdout_lines }}"

- name: Migrate app
  command: '/usr/bin/python /home/ubuntu/fitcycle/manage.py migrate'
  register: migrate_app

- name: Restart fitcycle app
  shell: nohup ./startfitcycle.sh & chdir=/home/ubuntu/fitcycle
  register: fitout

- name: Status of fitcycle app
  debug:
   msg: fitout
